version: "3.7"
services:
          # db:
          #     image: postgres
          #     container_name: postgres
          #     networks:
          #         - docker-network
          #     ports:
          #       - "5432:5432"
          #     volumes:
          #       - db:/var/lib/postgresql/data
          #       - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
          #     environment:
          #       - POSTGRES_PASSWORD: ${DB_PASSWORD}
          #       - POSTGRES_USER: ${DB_USER}
          #       - POSTGRES_DB: ${DB_NAME}
          #     networks:
          #       - docker-network
          #     restart: always
          # api:
          #     container_name: pong
          #     build: back-end/
          #     image: pong
          #     depends_on:
          #       - db
          #     ports:
          #       - "3000:3000"
          #     networks:
          #       - docker-network
          #     restart: always
          front:
                build: front/
                image: front-end
                container_name: front-end
                ports:
                        - "443:443"
                env_file:
                        - .env
                networks:
                        - docker-network
                restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/adamiens/data/db'
networks:
        docker-network:
                driver: bridge

